### ISSUE TITLE
Дамп структуры базы данных

### ISSUE THREAD

**Issue by vladciphersky** [ronandevru/spnews#1]
**Категория:** идея, предложение

Если не трудно, то можно в репозиторий кинуть дамп базы данных, чтобы разработчикам для тестирования и запуска не вручную её собирать?

**Comment by ronandevru** [comment]
https://gist.github.com/ronandevru/722a515bf6add77a078fdb63b934eac4

**Comment by vladciphersky** [comment]
thanks very much
